### ISSUE TITLE
Changing order of placeholders in translations

### ISSUE THREAD

**Issue by SafaAlfulaij** [teeworlds/teeworlds-translation#51]
There are some strings that have 2 placeholders, I think we can't change thier order.
An example:
The %s flag was captured by '%s'
In some languages the subject must be first..
{someone} captured the {color} flag

**Comment by Dune-jr** [comment]
@heinrich5991 I don't believe translators can specify the order of the strings? e.g. "The %s2 flag was captured by %s1"

**Comment by heinrich5991** [comment]
Indeed, we don't have that capability right now. I believe glibc would support that, but not every libc does, and I'd be surprised if the MSVC++ one did.

**Comment by Dune-jr** [comment]
Fixed by https://github.com/teeworlds/teeworlds/pull/2032
