### ISSUE TITLE
Gaelic Scottish needs a flag and Scotland isn't in ISO 3166-1

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds-translation#59]
The problem is that Scotland does not have an ISO 3166-1 code **but** it has a flag in Teeworlds, so technically we could use it.

I was forced to give the UK flag for now, which is confusing because English uses the same:

![screenshot_2018-11-10_22-05-26](https://user-images.githubusercontent.com/355114/48306025-e6eaae80-e534-11e8-909b-ec3a4938c15d.png)

Unless I'm mistaken on something, this seems like a code issue to me - alphabetic flag codes should probably be used instead of their numeric counterparts.

**Comment by Dune-jr** [comment]
@oy should we have another way of referring to flags than their ISO 3166-1 code, since some flags do *not* have such a numerical code?

**Comment by oy** [comment]
There're custom entries for countries which don't have an ISO 3166-1 code. 
https://github.com/teeworlds/teeworlds/blob/master/datasrc/countryflags/index.json#L16 That's the scottish one

**Comment by Dune-jr** [comment]
Ah, thanks @oy :)
