### ISSUE TITLE
Author information is now missing

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds-translation#60]
It seems like a different script than the trunk `reconvert_l10n` was used to generate the language files and add author info. How was this done?

**Comment by oy** [comment]
When updating a language file you added a new entry by hand. The script just loaded/stored the old entries.
https://github.com/teeworlds/teeworlds/blob/b03b498246309e66d68af8708a33f06fe2b17c67/scripts/update_localization.py that was the old script

**Comment by Dune-jr** [comment]
Previous author info restored by 4a6f63b9722d42bba30f5e6adca73e949b235c7a and 8c6172f09e6f7708824c56601000f1852719ee82.

I will add author info from Transifex when translations are closed.

**Comment by Dune-jr** [comment]
Closed by 121a8eb20a26196077f2b84f48b5d6fcbdf2fa33
