### ISSUE TITLE
Add a bit of context to these translations

### ISSUE THREAD

**Issue by savander** [teeworlds/teeworlds-translation#65]
If I will find more, I will updated or create new issue :)

1. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/23348936
2. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/159839345 
3. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/157088798
4. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/23348942
5. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/23348793
6. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/157088813
7. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/23348922
8. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/23348870
9. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/23348823
10. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/23348988
11. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/159839347
12. https://www.transifex.com/teeworlds/teeworlds/translate/#pl/teeworlds/157088806

**Comment by Dune-jr** [comment]
Fixed in https://github.com/teeworlds/teeworlds/pull/1800
