### ISSUE TITLE
Fix Chinese (traditional) language name

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds-translation#67]
I got confused by "Chinese" (汉语) not only referring to the least common of the two (traditional), but also being written in simplified chinese:

https://github.com/teeworlds/teeworlds-translation/blob/3a185e62de75fba32ec524836ce62f8ef0b2c9a3/index.json#L187-L195

Two solutions:
- keep "Simplified Chinese" as it is; rename "Chinese" (汉语, written in simplified chinese) to 繁體中文 ("Traditional Chinese", written in traditional chinese)
- rename "Simplified Chinese" (简体中文) to 汉语 (chinese, written in simplified chinese) and "Chinese" to 漢語 (chinese, written in traditional chinese)

I think the latter is most elegant.
Files should be renamed too.

Edit: Transifex refers to them as Chinese and Chinese (TW)

Resources: https://en.wikipedia.org/wiki/Chinese_language
Tagging @TsFreddie

**Comment by weez15** [comment]
The former is more common. There is nearly no site which uses the second solution.

**Comment by Dune-jr** [comment]
Thanks, @weez15. So 简体中文 for ZH and 繁體中文 for TW/HK.

**Comment by Dune-jr** [comment]
Closed by https://github.com/teeworlds/teeworlds-translation/commit/cf262a01ed15dd07ea92ccda52c6481d16238f7d
