### ISSUE TITLE
%1.f in string is not tagged by Transifex

### ISSUE THREAD

**Issue by Dune-jr** [teeworlds/teeworlds-translation#72]
![image](https://user-images.githubusercontent.com/355114/54957973-8e9cd200-4f54-11e9-9465-0611b0a9348d.png)
(report from @MertenNor)

Should that be `%.1f`, @oy?

**Comment by oy** [comment]
@Dune-jr no it's correct

**Comment by Dune-jr** [comment]
@oy Transifex does not recognize it as a string. It's a (minor) issue for translators. Is there no alternative format for `%.1f`?

**Comment by oy** [comment]
Does "%1.0f" work?

**Comment by Dune-jr** [comment]
Fixed by https://github.com/teeworlds/teeworlds/commit/da41a0973d191bc0c0df228006fac2c34bc6967d and temporarily fixed for 0.7.3.1. by https://github.com/teeworlds/teeworlds-translation/commit/9e543d9c8e8120631e183725825a064c59f3294e for erroneous translations in transi:muscle:
