### ISSUE TITLE
Slovak.json is actually in Slovenian, not Slovak

### ISSUE THREAD

**Issue by diznq** [teeworlds/teeworlds-translation#75]
This commit entirely wiped out correct slovak.json file and instead replaced it with slovenian translations

https://github.com/teeworlds/teeworlds-translation/commit/5c26696437594b86cfb54abb3f45d6c9739b8ee7

**Comment by Dune-jr** [comment]
@diznq Strange, looking into that asap

**Comment by Dune-jr** [comment]
@diznq Slovak was restored as an option on Transifex, but https://raw.githubusercontent.com/teeworlds/teeworlds-translation/503ac9b16b645b00095dbbbbc32440c46a588a42/slovak.json still needs to be ported over there as to save you some duplicate work

**Comment by Dune-jr** [comment]
@dizniq should be good
